var ARTISTS_DATA = {
    groc: {
        name: 'Groc',
        slug: 'groc',
        profileImage: '../assets/artists/groc/profile.png',
        pageUrl: '../index.html',
        bio: 'Groc is a tattoo artist in Tel Aviv specialising in calligraphy, black work, and freehand tattoos. His approach blends flowing script with bold black ink, creating pieces that feel both precise and alive — each one drawn freehand, no stencils, no shortcuts.',
        galleryImages: [
            '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg',
            '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg',
            '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg',
            '16.jpg', '17.jpg', '18.jpg', '19.jpg', '20.jpg',
            '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg',
            '26.jpg', '27.jpg', '28.jpg', '29.jpg', '30.jpg',
            '31.jpg', '32.jpg', '33.jpg', '34.jpg', '35.jpg',
            '36.jpg', '37.jpg', '38.jpg', '39.jpg'
        ],
        altTemplates: [
            'Freehand calligraphy tattoo by Groc, tattoo artist in Tel Aviv',
            'Black ink calligraphy piece at Sage Tattoo Studio Tel Aviv',
            'Bold freehand tattoo work by Groc, Tel Aviv tattoo artist',
            'Script lettering tattoo at a tattoo shop in Tel Aviv by Groc',
            'Detailed calligraphy tattoo by Groc, tattoo in Tel Aviv',
            'Freehand blackwork tattoo at Sage, a Tel Aviv tattoo studio',
            'Flowing script tattoo by Groc, a Tel Aviv tattoo artist',
            'Black ink freehand piece at Sage Tattoo Studio in Tel Aviv',
            'Calligraphy-style tattoo by Groc, tattoo artist Tel Aviv',
            'Bold freehand line work at a tattoo studio in Tel Aviv',
            'Script tattoo detail by Groc, Tel Aviv freehand specialist',
            'Black calligraphy tattoo at Sage tattoo shop, Tel Aviv',
            'Freehand tattoo in progress by Groc, tattoo in Tel Aviv',
            'Flowing blackwork piece by a Tel Aviv tattoo artist',
            'Calligraphy art tattoo at Sage Tattoo Studio Tel Aviv',
            'Precision freehand work by Groc, a tattoo artist in Tel Aviv',
            'Bold script tattoo at a tattoo studio in Tel Aviv-Yaffo',
            'Black ink calligraphy by Groc, Tel Aviv tattoo specialist',
            'Freehand lettering tattoo at Sage, a Tel Aviv tattoo shop',
            'Detailed blackwork by Groc, tattoo artist in Tel Aviv',
            'Flowing freehand tattoo at Sage Tattoo Studio in Tel Aviv',
            'Calligraphy blackwork piece by a Tel Aviv tattoo artist',
            'Script art tattoo by Groc, tattoo in Tel Aviv',
            'Bold freehand calligraphy at a Tel Aviv tattoo studio',
            'Black ink flowing script by Groc, Tel Aviv artist',
            'Freehand tattoo detail at Sage Tattoo Studio Tel Aviv',
            'Calligraphy piece by Groc, a tattoo artist in Tel Aviv',
            'Freehand blackwork tattoo at a tattoo shop in Tel Aviv',
            'Script tattoo by Groc, Tel Aviv freehand tattoo artist',
            'Bold calligraphy ink work at Sage, Tel Aviv studio',
            'Freehand lettering by Groc, tattoo artist in Tel Aviv',
            'Flowing black script tattoo at Sage Tattoo Studio',
            'Calligraphy freehand piece by a Tel Aviv tattoo artist',
            'Black ink script tattoo by Groc, tattoo in Tel Aviv',
            'Freehand calligraphy at a tattoo studio in Tel Aviv',
            'Bold script work by Groc, Tel Aviv tattoo specialist',
            'Flowing calligraphy tattoo at Sage, a Tel Aviv tattoo shop',
            'Freehand black ink piece by Groc, Tel Aviv artist',
            'Script calligraphy tattoo at Sage Tattoo Studio Tel Aviv'
        ]
    },
    gosha: {
        name: 'Gosha',
        slug: 'gosha',
        profileImage: '../assets/artists/gosha/profile.png',
        pageUrl: '../index.html',
        bio: 'Gosha is a tattoo artist in Tel Aviv specialising in American Traditional tattoos. His bold lines, classic colour palettes, and timeless motifs bring old-school tattooing to Sage Tattoo Studio — crisp flash-driven designs that stay sharp for a lifetime.',
        galleryImages: [
            '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg',
            '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg',
            '11.jpg', '12.jpg'
        ],
        altTemplates: [
            'American Traditional tattoo by Gosha, tattoo artist in Tel Aviv',
            'Bold old-school tattoo piece at Sage Tattoo Studio Tel Aviv',
            'Classic traditional tattoo by Gosha, a Tel Aviv tattoo artist',
            'Bold colour tattoo at a tattoo shop in Tel Aviv by Gosha',
            'Old-school traditional work by Gosha, tattoo in Tel Aviv',
            'Bold line traditional tattoo at Sage, a Tel Aviv tattoo studio',
            'Classic american traditional tattoo by Gosha, Tel Aviv artist',
            'Bold ink piece at Sage Tattoo Studio in Tel Aviv by Gosha',
            'Traditional tattoo art by Gosha, tattoo artist Tel Aviv',
            'Old-school tattoo detail at a tattoo studio in Tel Aviv',
            'Bold american traditional work by Gosha, Tel Aviv tattoo artist',
            'Classic traditional tattoo at Sage Tattoo Studio Tel Aviv'
        ]
    },
    sunches: {
        name: 'Sunches',
        slug: 'sunches',
        profileImage: '../assets/artists/sunches/profile.png',
        pageUrl: '../index.html',
        bio: 'Sunches works in black and grey with an illustrative style that brings depth and mood to every piece. Known for original art tattoos and palm tattoo work, she creates custom designs at Sage tattoo studio in Tel Aviv that push the boundaries of what grey-wash can do.',
        galleryImages: [
            '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg',
            '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg',
            '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg',
            '16.jpg', '17.jpg', '18.jpg', '19.jpg', '20.jpg',
            '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg'
        ],
        altTemplates: [
            'Black and grey tattoo by Sunches, tattoo artist in Tel Aviv',
            'Illustrative grey-wash piece at Sage Tattoo Studio Tel Aviv',
            'Palm tattoo by Sunches, a Tel Aviv tattoo artist',
            'Original art tattoo at a tattoo shop in Tel Aviv by Sunches',
            'Detailed black and grey work by Sunches, Tel Aviv artist',
            'Illustrative tattoo at Sage, a Tel Aviv tattoo studio',
            'Grey-wash tattoo by Sunches, tattoo artist in Tel Aviv',
            'Palm tattoo detail at Sage Tattoo Studio in Tel Aviv',
            'Original art piece by Sunches, a Tel Aviv tattoo specialist',
            'Black and grey illustrative work at a Tel Aviv tattoo studio',
            'Palm tattoo by Sunches, tattoo in Tel Aviv',
            'Grey-wash illustration at Sage tattoo shop, Tel Aviv',
            'Original art tattoo by Sunches, Tel Aviv artist',
            'Detailed black and grey piece at Sage Tattoo Studio Tel Aviv',
            'Illustrative palm tattoo by a Tel Aviv tattoo artist',
            'Black and grey work by Sunches, tattoo artist Tel Aviv',
            'Grey-wash tattoo at a tattoo studio in Tel Aviv-Yaffo',
            'Palm tattoo detail by Sunches, Tel Aviv tattoo specialist',
            'Original illustrative tattoo at Sage, a Tel Aviv tattoo shop',
            'Black and grey art by Sunches, a tattoo artist in Tel Aviv',
            'Illustrative tattoo piece at Sage Tattoo Studio Tel Aviv',
            'Palm tattoo work by Sunches, tattoo in Tel Aviv',
            'Grey-wash illustrative tattoo at a Tel Aviv tattoo studio',
            'Original art piece by Sunches, Tel Aviv tattoo artist',
            'Black and grey palm tattoo at Sage Tattoo Studio Tel Aviv'
        ]
    }
};
